import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthSessionProvider from './provider/sessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body className={inter.className}>{children}</body>
      </NextAuthSessionProvider>
    </html>
  )
}
